### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by Alir3z4** [iMakedonsky/drf-autodocs#15]
I get the following error when I try to open the URL.

Versions:
Django==1.10.7
djangorestframework==3.6.3

```
[20/Jun/2017 18:32:22] ERROR [django.request:132] Internal Server Error: /api/docs/
Traceback (most recent call last):
  File "/home/alireza/.virtualenvs/hello/lib/python3.6/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/alireza/.virtualenvs/hello/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/alireza/.virtualenvs/hello/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/alireza/.virtualenvs/hello/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alireza/.virtualenvs/hello/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/alireza/.virtualenvs/hello/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/alireza/.virtualenvs/hello/lib/python3.6/site-packages/django/views/generic/base.py", line 155, in get
    context = self.get_context_data(**kwargs)
  File "/home/alireza/.virtualenvs/hello/lib/python3.6/site-packages/drf_autodocs/views.py", line 11, in get_context_data
    context['endpoints_tree'] = TreeAPIParser().endpoints_tree.to_dict()
  File "/home/alireza/.virtualenvs/hello/lib/python3.6/site-packages/drf_autodocs/parser.py", line 44, in __init__
    super().__init__(*args, **kwargs)
  File "/home/alireza/.virtualenvs/hello/lib/python3.6/site-packages/drf_autodocs/parser.py", line 27, in __init__
    self.parse()
  File "/home/alireza/.virtualenvs/hello/lib/python3.6/site-packages/drf_autodocs/parser.py", line 47, in parse
    self.parse_tree(self.patterns, self.endpoints_tree)
  File "/home/alireza/.virtualenvs/hello/lib/python3.6/site-packages/drf_autodocs/parser.py", line 60, in parse_tree
    api_endpoint = Endpoint(pattern, prefix)
  File "/home/alireza/.virtualenvs/hello/lib/python3.6/site-packages/drf_autodocs/endpoint.py", line 21, in __init__
    self.name = self._get_endpoint_name()
  File "/home/alireza/.virtualenvs/hello/lib/python3.6/site-packages/drf_autodocs/endpoint.py", line 63, in _get_endpoint_name
    return self.pattern.name.replace('-', ' ').replace('_', ' ').title()
AttributeError: 'NoneType' object has no attribute 'replace'
[20/Jun/2017 18:32:23] ERROR [django.server:131] "GET /api/docs/ HTTP/1.1" 500 122939
```

**Comment by iMakedonsky** [comment]
Thanks for report.
Could you please provide you urls and views files?

**Comment by bobozar** [comment]
Getting the same error.             

`return self.pattern.name.replace('-', ' ').replace('_', ' ').title()`

The line is the culprit.

**Comment by Gobiviswa** [comment]
is this error solved?

**Comment by Mohamadhassan98** [comment]
This is because you haven't specified 'name' attribute for (at least) one of your urls, and you didn't set AUTODOCS_ENDPOINT_NAMES = "view" in your settings.py.
Either set it in the settings to use your view name as Endpoint name, or specify each name for urls instead.
